/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Modes */
        get: operations["list_modes_api_modes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modes/{mode_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mode */
        get: operations["get_mode_api_modes__mode_id__get"];
        /** Update Mode */
        put: operations["update_mode_api_modes__mode_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modes/{mode_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Mode */
        post: operations["reset_mode_api_modes__mode_id__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_api_projects__project_id__chat_get"];
        put?: never;
        /** Send */
        post: operations["send_api_projects__project_id__chat_post"];
        /** Clear */
        delete: operations["clear_api_projects__project_id__chat_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/chat/{message_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply */
        post: operations["apply_api_projects__project_id__chat__message_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/chat/{message_id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discard */
        post: operations["discard_api_projects__project_id__chat__message_id__discard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/compass": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compass */
        get: operations["compass_api_projects__project_id__compass_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_projects__project_id__dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate */
        post: operations["evaluate_api_projects__project_id__evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/evaluations/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Evaluation */
        get: operations["latest_evaluation_api_projects__project_id__evaluations_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Feedback */
        post: operations["add_feedback_api_projects__project_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_projects__project_id__items_get"];
        put?: never;
        /** Create Item */
        post: operations["create_item_api_projects__project_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/items/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Create */
        post: operations["bulk_create_api_projects__project_id__items_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Item */
        delete: operations["delete_item_api_projects__project_id__items__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["update_item_api_projects__project_id__items__item_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reports */
        get: operations["list_reports_api_projects__project_id__reports_get"];
        put?: never;
        /** Create Report */
        post: operations["create_report_api_projects__project_id__reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/tasks/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Tasks */
        post: operations["extract_tasks_api_projects__project_id__tasks_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alert */
        Alert: {
            /** Alignment Score */
            alignment_score: number;
            /** Content Hash */
            content_hash: string;
            /** Reason */
            reason: string;
            /** Suggested Action */
            suggested_action: string;
            /** Task Id */
            task_id: string;
            /** Title */
            title: string;
            verdict: components["schemas"]["Verdict"];
        };
        /** Assumption */
        Assumption: {
            /** Created At */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Id */
            id: string;
            /** @default medium */
            priority: components["schemas"]["Priority"];
            /** Projectid */
            projectId: string;
            /** @default untested */
            status: components["schemas"]["AssumptionStatus"];
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "assumption";
            /** Updated At */
            updated_at: string;
        };
        /** AssumptionFields */
        AssumptionFields: {
            /** @default medium */
            priority?: components["schemas"]["Priority"];
            /** @default untested */
            status?: components["schemas"]["AssumptionStatus"];
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "assumption";
        };
        /** AssumptionSeed */
        AssumptionSeed: {
            /** @default medium */
            priority?: components["schemas"]["Priority"];
            /** Text */
            text: string;
        };
        /**
         * AssumptionStatus
         * @enum {string}
         */
        AssumptionStatus: "untested" | "testing" | "supported" | "rejected";
        /** BulkTaskCreate */
        BulkTaskCreate: {
            /** Tasks */
            tasks: components["schemas"]["TaskFields"][];
        };
        /** CardLabels */
        CardLabels: {
            /** Deadline Risk */
            deadline_risk: string;
            /** Deadline Risk Hint */
            deadline_risk_hint: string;
            /** Drift */
            drift: string;
            /** Drift Hint */
            drift_hint: string;
            /** Under Evidenced Title */
            under_evidenced_title: string;
            /** Unnecessary */
            unnecessary: string;
            /** Unnecessary Hint */
            unnecessary_hint: string;
            /** Untested */
            untested: string;
            /** Untested Hint */
            untested_hint: string;
            /** Weak Tasks Title */
            weak_tasks_title: string;
        };
        /** Cards */
        Cards: {
            /** Deadline Risk */
            deadline_risk: number;
            /** Drift */
            drift: number;
            /** Unnecessary */
            unnecessary: number;
            /** Untested */
            untested: number;
        };
        /** ChatApply */
        ChatApply: {
            /** Operation Indexes */
            operation_indexes?: number[] | null;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Content */
            content: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Projectid */
            projectId: string;
            proposal: components["schemas"]["Proposal"] | null;
            role: components["schemas"]["ChatRole"];
            /** User Email */
            user_email: string;
        };
        /**
         * ChatRole
         * @enum {string}
         */
        ChatRole: "user" | "assistant";
        /** ChatSend */
        ChatSend: {
            /** Message */
            message: string;
        };
        /** ChatSendResponse */
        ChatSendResponse: {
            assistant_message: components["schemas"]["ChatMessage"];
            user_message: components["schemas"]["ChatMessage"];
        };
        /** Compass */
        Compass: {
            /** Attention Count */
            attention_count: number;
            /** Delta Vs Last Month */
            delta_vs_last_month: number | null;
            /** Frames */
            frames: components["schemas"]["CompassFrame"][];
            /** Health Score */
            health_score: number | null;
            /** Sectors */
            sectors: components["schemas"]["CompassSector"][];
            /** Tasks */
            tasks: components["schemas"]["CompassTask"][];
        };
        /** CompassFrame */
        CompassFrame: {
            /** Date */
            date: string;
            /** Health Score */
            health_score: number | null;
            /** Is Current */
            is_current: boolean;
        };
        /** CompassPoint */
        CompassPoint: {
            /** Score */
            score: number;
            verdict: components["schemas"]["Verdict"];
        };
        /** CompassSector */
        CompassSector: {
            /** Id */
            id: string;
            priority: components["schemas"]["Priority"];
            /** Text */
            text: string;
        };
        /** CompassTask */
        CompassTask: {
            feedback: components["schemas"]["FeedbackJudgement"] | null;
            /** Needs Attention */
            needs_attention: boolean;
            /** Points */
            points: (components["schemas"]["CompassPoint"] | null)[];
            /** Reason */
            reason: string;
            /** Sector Id */
            sector_id: string | null;
            status: components["schemas"]["TaskStatus"];
            /** Suggested Action */
            suggested_action: string;
            /** Task Id */
            task_id: string;
            /** Title */
            title: string;
        };
        /** Criterion */
        Criterion: {
            /** Created At */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Id */
            id: string;
            /** Projectid */
            projectId: string;
            /** @default not_met */
            status: components["schemas"]["CriterionStatus"];
            /**
             * Target
             * @default
             */
            target: string;
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "criterion";
            /** Updated At */
            updated_at: string;
        };
        /** CriterionFields */
        CriterionFields: {
            /** @default not_met */
            status?: components["schemas"]["CriterionStatus"];
            /**
             * Target
             * @default
             */
            target?: string;
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "criterion";
        };
        /** CriterionSeed */
        CriterionSeed: {
            /**
             * Target
             * @default
             */
            target?: string;
            /** Text */
            text: string;
        };
        /**
         * CriterionStatus
         * @enum {string}
         */
        CriterionStatus: "not_met" | "met";
        /** Dashboard */
        Dashboard: {
            /** Alerts */
            alerts: components["schemas"]["Alert"][];
            cards: components["schemas"]["Cards"];
            /** Deadline Risks */
            deadline_risks: components["schemas"]["DeadlineRiskItem"][];
            /** Design Changed */
            design_changed: boolean;
            /** Evidence Tally */
            evidence_tally: components["schemas"]["EvidenceTally"][];
            health: components["schemas"]["HealthView"];
            /** Last Evaluated At */
            last_evaluated_at: string | null;
            schedule: components["schemas"]["ScheduleView"];
            /** Stale Task Ids */
            stale_task_ids: string[];
            /** Trend */
            trend: components["schemas"]["TrendPoint"][];
            /** Under Evidenced */
            under_evidenced: components["schemas"]["UnderEvidenced"][];
            /** Unevaluated Task Ids */
            unevaluated_task_ids: string[];
            verdict_counts: components["schemas"]["VerdictCounts"];
            /** Weak Tasks */
            weak_tasks: components["schemas"]["WeakTask"][];
        };
        /** DeadlineRiskItem */
        DeadlineRiskItem: {
            /** Item Id */
            item_id: string;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
        };
        /**
         * Decision
         * @enum {string}
         */
        Decision: "continue" | "pivot" | "stop";
        /** DecisionFields */
        DecisionFields: {
            decision: components["schemas"]["Decision"];
            /**
             * Note
             * @default
             */
            note?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "decision";
        };
        /** DecisionItem */
        DecisionItem: {
            /** Created At */
            created_at: string;
            /** Created By */
            created_by: string;
            decision: components["schemas"]["Decision"];
            /** Id */
            id: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Projectid */
            projectId: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "decision";
            /** Updated At */
            updated_at: string;
        };
        /** Evaluation */
        Evaluation: {
            /**
             * Ai Calls
             * @default 0
             */
            ai_calls: number;
            /** Created At */
            created_at: string;
            /** Design Hash */
            design_hash: string;
            /** Id */
            id: string;
            /** Model */
            model: string;
            /** Projectid */
            projectId: string;
            /** Task Results */
            task_results: components["schemas"]["TaskResult"][];
            trigger: components["schemas"]["EvaluationTrigger"];
            /** Unevaluated Task Ids */
            unevaluated_task_ids: string[];
        };
        /**
         * EvaluationTrigger
         * @enum {string}
         */
        EvaluationTrigger: "manual" | "scheduled";
        /** Evidence */
        Evidence: {
            /** Assumption Id */
            assumption_id: string;
            /** Created At */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Id */
            id: string;
            /** Projectid */
            projectId: string;
            result: components["schemas"]["EvidenceResult"];
            /**
             * Source
             * @default
             */
            source: string;
            /** Summary */
            summary: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "evidence";
            /** Updated At */
            updated_at: string;
        };
        /** EvidenceFields */
        EvidenceFields: {
            /** Assumption Id */
            assumption_id: string;
            result: components["schemas"]["EvidenceResult"];
            /**
             * Source
             * @default
             */
            source?: string;
            /** Summary */
            summary: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "evidence";
        };
        /**
         * EvidenceResult
         * @enum {string}
         */
        EvidenceResult: "supports" | "refutes" | "inconclusive";
        /** EvidenceTally */
        EvidenceTally: {
            /** Assumption Id */
            assumption_id: string;
            /** Inconclusive */
            inconclusive: number;
            /** Refutes */
            refutes: number;
            /** Supports */
            supports: number;
            /** Text */
            text: string;
        };
        /** ExtractRequest */
        ExtractRequest: {
            /** Text */
            text: string;
        };
        /** ExtractResponse */
        ExtractResponse: {
            /** Tasks */
            tasks: components["schemas"]["ExtractedTask"][];
        };
        /** ExtractedTask */
        ExtractedTask: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Linked Assumption Ids */
            linked_assumption_ids: string[];
            /** Linked Criterion Ids */
            linked_criterion_ids: string[];
            /** Title */
            title: string;
        };
        /** Feedback */
        Feedback: {
            /** Content Hash */
            content_hash: string;
            /** Created At */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Id */
            id: string;
            judgement: components["schemas"]["FeedbackJudgement"];
            /** Projectid */
            projectId: string;
            /** Task Id */
            task_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "feedback";
            /** Updated At */
            updated_at: string;
        };
        /** FeedbackCreate */
        FeedbackCreate: {
            judgement: components["schemas"]["FeedbackJudgement"];
            /** Task Id */
            task_id: string;
        };
        /**
         * FeedbackJudgement
         * @enum {string}
         */
        FeedbackJudgement: "agree" | "dismiss";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthComponents */
        HealthComponents: {
            /** Alignment */
            alignment: number | null;
            /** Schedule */
            schedule: number | null;
            /** Validation */
            validation: number | null;
            /** Waste */
            waste: number | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ai Configured */
            ai_configured: boolean;
            /** Status */
            status: string;
            /** Storage */
            storage: string;
        };
        /** HealthView */
        HealthView: {
            components: components["schemas"]["HealthComponents"];
            /** Computed At */
            computed_at: string | null;
            /** Delta Vs Last Month */
            delta_vs_last_month: number | null;
            /** Score */
            score: number | null;
        };
        /**
         * ItemPatch
         * @description Partial update. The service merges it into the stored item and re-validates with the type's model.
         */
        ItemPatch: {
            /**
             * Clear Due Date
             * @default false
             */
            clear_due_date?: boolean;
            /**
             * Clear Effort Hours
             * @default false
             */
            clear_effort_hours?: boolean;
            /**
             * Clear Start Date
             * @default false
             */
            clear_start_date?: boolean;
            /** Description */
            description?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Effort Hours */
            effort_hours?: number | null;
            /** Linked Assumption Ids */
            linked_assumption_ids?: string[] | null;
            /** Linked Criterion Ids */
            linked_criterion_ids?: string[] | null;
            /** Note */
            note?: string | null;
            priority?: components["schemas"]["Priority"] | null;
            result?: components["schemas"]["EvidenceResult"] | null;
            /** Source */
            source?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** Status */
            status?: string | null;
            /** Summary */
            summary?: string | null;
            /** Target */
            target?: string | null;
            /** Text */
            text?: string | null;
            /** Title */
            title?: string | null;
        };
        /**
         * Mode
         * @enum {string}
         */
        Mode: "poc" | "planning" | "improvement";
        /** ModeDefinition */
        ModeDefinition: {
            card_labels: components["schemas"]["CardLabels"];
            /** Description */
            description: string;
            id: components["schemas"]["Mode"];
            labels: components["schemas"]["ModeLabels"];
            /** Name */
            name: string;
            placeholders: components["schemas"]["Placeholders"];
            /** Prompt Guidance */
            prompt_guidance: string;
            /** Updated At */
            updated_at: string | null;
            /** Updated By */
            updated_by: string | null;
            weights: components["schemas"]["Weights"];
        };
        /** ModeDefinitionBody */
        ModeDefinitionBody: {
            card_labels: components["schemas"]["CardLabels"];
            /** Description */
            description: string;
            labels: components["schemas"]["ModeLabels"];
            /** Name */
            name: string;
            placeholders: components["schemas"]["Placeholders"];
            /** Prompt Guidance */
            prompt_guidance: string;
            weights: components["schemas"]["Weights"];
        };
        /** ModeLabels */
        ModeLabels: {
            /** Assumption */
            assumption: string;
            /** Criterion */
            criterion: string;
            /** Deadline */
            deadline: string;
            /** Decision Continue */
            decision_continue: string;
            /** Decision Pivot */
            decision_pivot: string;
            /** Decision Stop */
            decision_stop: string;
            /** Evidence */
            evidence: string;
            /** Goal */
            goal: string;
            /** Task */
            task: string;
        };
        /** Operation */
        Operation: {
            /** Error */
            error: string | null;
            /** Fields */
            fields: {
                [key: string]: unknown;
            };
            /** Item Id */
            item_id: string | null;
            op: components["schemas"]["OperationKind"];
            /** Result */
            result: string | null;
            /** Result Message */
            result_message: string | null;
            /** Summary */
            summary: string;
            target: components["schemas"]["OperationTarget"];
        };
        /**
         * OperationKind
         * @enum {string}
         */
        OperationKind: "create" | "update" | "delete";
        /**
         * OperationTarget
         * @enum {string}
         */
        OperationTarget: "assumption" | "criterion" | "task" | "evidence" | "project";
        /** Placeholders */
        Placeholders: {
            /** Assumption */
            assumption: string;
            /** Criterion */
            criterion: string;
            /** Evidence */
            evidence: string;
            /** Goal */
            goal: string;
            /** Task */
            task: string;
            /** Title */
            title: string;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "high" | "medium" | "low";
        /** Project */
        Project: {
            /** Created At */
            created_at: string;
            /**
             * Deadline
             * Format: date
             */
            deadline: string;
            /**
             * Deleted
             * @default false
             */
            deleted: boolean;
            /** Goal */
            goal: string;
            /** Id */
            id: string;
            /** Members */
            members: string[];
            mode: components["schemas"]["Mode"];
            /** Owner Email */
            owner_email: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** @default active */
            status: components["schemas"]["ProjectStatus"];
            summary: components["schemas"]["ProjectSummary"];
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Assumptions */
            assumptions?: components["schemas"]["AssumptionSeed"][];
            /** Criteria */
            criteria?: components["schemas"]["CriterionSeed"][];
            /**
             * Deadline
             * Format: date
             */
            deadline: string;
            /** Goal */
            goal: string;
            /** Members */
            members?: string[];
            mode: components["schemas"]["Mode"];
            /** Start Date */
            start_date?: string | null;
            /** Title */
            title: string;
        };
        /** ProjectItems */
        ProjectItems: {
            /** Assumptions */
            assumptions: components["schemas"]["Assumption"][];
            /** Criteria */
            criteria: components["schemas"]["Criterion"][];
            /** Decisions */
            decisions: components["schemas"]["DecisionItem"][];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Feedback */
            feedback: components["schemas"]["Feedback"][];
            /** Tasks */
            tasks: components["schemas"]["Task"][];
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "active" | "stopped" | "completed";
        /**
         * ProjectSummary
         * @description Snapshot of dashboard numbers stored on the project at evaluation time (for the list view).
         */
        ProjectSummary: {
            /**
             * Deadline Risk
             * @default 0
             */
            deadline_risk: number;
            /**
             * Drift
             * @default 0
             */
            drift: number;
            /** Evaluated At */
            evaluated_at: string | null;
            /** Health Score */
            health_score: number | null;
            /**
             * Unnecessary
             * @default 0
             */
            unnecessary: number;
            /**
             * Untested
             * @default 0
             */
            untested: number;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Deadline */
            deadline?: string | null;
            /** Goal */
            goal?: string | null;
            /** Members */
            members?: string[] | null;
            mode?: components["schemas"]["Mode"] | null;
            /** Start Date */
            start_date?: string | null;
            status?: components["schemas"]["ProjectStatus"] | null;
            /** Title */
            title?: string | null;
        };
        /** Proposal */
        Proposal: {
            /** Operations */
            operations: components["schemas"]["Operation"][];
            status: components["schemas"]["ProposalStatus"];
        };
        /**
         * ProposalStatus
         * @enum {string}
         */
        ProposalStatus: "pending" | "applied" | "partially_applied" | "discarded";
        /** Report */
        Report: {
            content: components["schemas"]["ReportContent"];
            /** Created At */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Health Score */
            health_score: number | null;
            /** Id */
            id: string;
            /** Model */
            model: string;
            /** Projectid */
            projectId: string;
        };
        /** ReportContent */
        ReportContent: {
            /** Highlights */
            highlights: string[];
            /** Next Actions */
            next_actions: string[];
            /** Options */
            options: components["schemas"]["ReportOption"][];
            /** Questions */
            questions: string[];
            /** Summary */
            summary: string;
        };
        /** ReportOption */
        ReportOption: {
            /** Concerns */
            concerns: string[];
            /** Conditions */
            conditions: string[];
            decision: components["schemas"]["Decision"];
            /** Supporting */
            supporting: string[];
        };
        /** ScheduleView */
        ScheduleView: {
            /** Days Left */
            days_left: number;
            /** Delayed */
            delayed: boolean;
            /** Elapsed */
            elapsed: number;
            /** Progress */
            progress: number;
        };
        /** Task */
        Task: {
            /** Created At */
            created_at: string;
            /** Created By */
            created_by: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Due Date */
            due_date: string | null;
            /** Effort Hours */
            effort_hours: number | null;
            /** Id */
            id: string;
            /** Linked Assumption Ids */
            linked_assumption_ids: string[];
            /** Linked Criterion Ids */
            linked_criterion_ids: string[];
            /** Projectid */
            projectId: string;
            /** Start Date */
            start_date: string | null;
            /** @default todo */
            status: components["schemas"]["TaskStatus"];
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "task";
            /** Updated At */
            updated_at: string;
        };
        /** TaskFields */
        TaskFields: {
            /**
             * Description
             * @default
             */
            description?: string;
            /** Due Date */
            due_date?: string | null;
            /** Effort Hours */
            effort_hours?: number | null;
            /** Linked Assumption Ids */
            linked_assumption_ids?: string[];
            /** Linked Criterion Ids */
            linked_criterion_ids?: string[];
            /** Start Date */
            start_date?: string | null;
            /** @default todo */
            status?: components["schemas"]["TaskStatus"];
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "task";
        };
        /** TaskResult */
        TaskResult: {
            /** Alignment Score */
            alignment_score: number;
            /** Content Hash */
            content_hash: string;
            /** Linked Assumption Ids */
            linked_assumption_ids: string[];
            /** Linked Criterion Ids */
            linked_criterion_ids: string[];
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Reused
             * @default false
             */
            reused: boolean;
            /**
             * Suggested Action
             * @default
             */
            suggested_action: string;
            /** Task Id */
            task_id: string;
            verdict: components["schemas"]["Verdict"];
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "todo" | "doing" | "done";
        /** TrendPoint */
        TrendPoint: {
            /** Date */
            date: string;
            /** Score */
            score: number | null;
        };
        /** UnderEvidenced */
        UnderEvidenced: {
            /** Assumption Id */
            assumption_id: string;
            /** Evidence Count */
            evidence_count: number;
            priority: components["schemas"]["Priority"];
            /** Shortage */
            shortage: number;
            /** Text */
            text: string;
        };
        /** UserContext */
        UserContext: {
            /** Email */
            email: string;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Verdict
         * @enum {string}
         */
        Verdict: "aligned" | "weak" | "drift" | "unnecessary_candidate";
        /** VerdictCounts */
        VerdictCounts: {
            /** Aligned */
            aligned: number;
            /** Dismissed */
            dismissed: number;
            /** Drift */
            drift: number;
            /** Pending */
            pending: number;
            /** Unnecessary */
            unnecessary: number;
            /** Weak */
            weak: number;
        };
        /** WeakTask */
        WeakTask: {
            /** Alignment Score */
            alignment_score: number;
            /** Gap */
            gap: number;
            /** Reason */
            reason: string;
            /** Task Id */
            task_id: string;
            /** Title */
            title: string;
            verdict: components["schemas"]["Verdict"];
        };
        /** Weights */
        Weights: {
            /** Alignment */
            alignment: number;
            /** Schedule */
            schedule: number;
            /** Validation */
            validation: number;
            /** Waste */
            waste: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserContext"];
                };
            };
        };
    };
    list_modes_api_modes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModeDefinition"][];
                };
            };
        };
    };
    get_mode_api_modes__mode_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModeDefinition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_mode_api_modes__mode_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mode_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModeDefinitionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModeDefinition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_mode_api_modes__mode_id__reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModeDefinition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: {
                mode?: components["schemas"]["Mode"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_projects__project_id__chat_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_api_projects__project_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatSend"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_api_projects__project_id__chat_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_api_projects__project_id__chat__message_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ChatApply"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_api_projects__project_id__chat__message_id__discard_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compass_api_projects__project_id__compass_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Compass"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_projects__project_id__dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_api_projects__project_id__evaluations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evaluation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_evaluation_api_projects__project_id__evaluations_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evaluation"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_feedback_api_projects__project_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assumption"] | components["schemas"]["Criterion"] | components["schemas"]["Task"] | components["schemas"]["Evidence"] | components["schemas"]["DecisionItem"] | components["schemas"]["Feedback"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_projects__project_id__items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectItems"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_projects__project_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssumptionFields"] | components["schemas"]["CriterionFields"] | components["schemas"]["TaskFields"] | components["schemas"]["EvidenceFields"] | components["schemas"]["DecisionFields"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assumption"] | components["schemas"]["Criterion"] | components["schemas"]["Task"] | components["schemas"]["Evidence"] | components["schemas"]["DecisionItem"] | components["schemas"]["Feedback"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_create_api_projects__project_id__items_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkTaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["Assumption"] | components["schemas"]["Criterion"] | components["schemas"]["Task"] | components["schemas"]["Evidence"] | components["schemas"]["DecisionItem"] | components["schemas"]["Feedback"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_projects__project_id__items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_api_projects__project_id__items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assumption"] | components["schemas"]["Criterion"] | components["schemas"]["Task"] | components["schemas"]["Evidence"] | components["schemas"]["DecisionItem"] | components["schemas"]["Feedback"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_projects__project_id__reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_api_projects__project_id__reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_tasks_api_projects__project_id__tasks_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
